
name: Github Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Run Angular build
      run: npm run build